### ISSUE TITLE
Erro ao tentar acessar página depois da instalação

### ISSUE THREAD

**Issue by lpirola** [okfn-brasil/gastos_abertos_website#1]
Sigo os passos descritos no README e depois `fab run`.

Ao tentar acessar o endereço: http://localhost:8000/ o erro a seguir aparece.

```
127.0.0.1 - - [08/Feb/2015 23:05:34] "GET /pt_BR/Sobre/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lpirola/projects/gastos_abertos_website/site.py", line 122, in page
    return render_template(template, page=page, today=today, pages=pages)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lpirola/projects/gastos_abertos_website/templates/page.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/lpirola/projects/gastos_abertos_website/templates/base.html", line 33, in top-level template code
    {% block content %}
  File "/home/lpirola/projects/gastos_abertos_website/templates/page.html", line 4, in block "content"
    {{ page }}
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask_flatpages/__init__.py", line 114, in __html__
    return self.html
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/werkzeug/utils.py", line 71, in __get__
    value = self.func(obj)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask_flatpages/__init__.py", line 126, in html
    return self.html_renderer(self.body)
  File "/home/lpirola/.virtualenvs/py/lib/python2.7/site-packages/flask_flatpages/__init__.py", line 337, in wrapper
    return html_renderer(body)
  File "/home/lpirola/projects/gastos_abertos_website/site.py", line 87, in render_markdown
    return unicode(doc.html, 'utf8')
  File "build/bdist.linux-x86_64/egg/pandoc/core.py", line 65, in <lambda>
    (lambda x, fmt=fmt: cls._output(x, fmt)), # fget
  File "build/bdist.linux-x86_64/egg/pandoc/core.py", line 82, in _output
    stdout=subprocess.PIPE
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by aivuk** [comment]
Esqueci de comentar que é necessário possuir o Pandoc instalado. Adicioneu ao README:

https://github.com/okfn-brasil/gastos_abertos_website#install-pandoc
